version: '3'
services:
  web:
    build: ./my-app
    ports:
      - "4444:4444"
    volumes:
      - ./my-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=4444

  backend:
    build: ./backend
    ports:
      - "8189:8189"
    environment:
      - GIN_MODE=release
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=your_database
      - DB_PORT=3306
    volumes:
      - ./backend:/app
    command: ["/backend"]
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_database
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf

volumes:
  mysql-data:
